add KEEP_VOLUMES_NAMED feature
meltwater/docker-cleanup pull request #36
Opened 2016-12-06 12:23 UTC by msutter

This allows to pass a list of named volumes to keep.
Note that dangling unnamed volumes will always be removed.

2017-07-20 06:43 UTC, wzrdtales commented
An important addition. @meltwater Is there anything missing to merge this or is this project not longer maintained?

2017-07-25 23:35 UTC, jnjackins requested changes
I apologize that it has take so much time to give this attention. Please review my comments.

2017-07-25 23:35 UTC, jnjackins commented on README.md
> +By default, both are set to \*\*None\*\* which is the same as the blank string.  If you want to keep ALL images, containers or volumes then you should use \*\*All\*\* to match all items. Do not use a
You escaped the asterisks in the first `**All**`, but not the second.

2017-07-25 23:35 UTC, jnjackins commented on run.sh
> +      CONTAINER_NAME=$(docker inspect --format='{{(index .Name)}}' $CONTAINER_ID | sed 's/^\///')
This change seems unrelated.

2017-07-25 23:35 UTC, jnjackins commented on run.sh
> +        if [ ${#VOLUME_ID} -eq 64 ]; then
`if echo $VOLUME_ID |grep -q "[0-9a-fA-F]\{64\}"; then`

2017-07-25 23:35 UTC, jnjackins commented on run.sh
> +      DANGLING_VOLUMES_IDS="`docker volume ls -qf dangling=true | xargs echo`"
What was the purpose of changing this from `for volume in $(docker volume ls -qf dangling=true); do`?

2017-07-25 23:35 UTC, jnjackins commented on run.sh
> +        if [[ $PATTERN = '.' ]]; then
I don't understand how (or if) the old code here worked. Are you fixing a bug or adding new functionality?

2017-07-28 19:48 UTC, jnjackins commented
Fixes #32

2019-06-11 08:26 UTC, rasjoh commented
Won't fix due to retiring project

2019-06-11 08:26 UTC, closed without merging